// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7NjdfGI2ZLwuF0OThhSJygfjFAtEn9E',
    appId: '1:166422488084:web:4f4bc64b4d1018914cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    authDomain: 'buildapplications-27ce1.firebaseapp.com',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    measurementId: 'G-CSK08EHXVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGQ9iFrsGekooi3zjRiT1VMSC3Ht_37I',
    appId: '1:166422488084:android:85de88b0f36216814cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    storageBucket: 'buildapplications-27ce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OjknSOPGSM6aNoFmcLBngOC7fMD2qLw',
    appId: '1:166422488084:ios:f323b53bb97494424cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    iosBundleId: 'com.example.threePost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1OjknSOPGSM6aNoFmcLBngOC7fMD2qLw',
    appId: '1:166422488084:ios:f323b53bb97494424cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    iosBundleId: 'com.example.threePost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7NjdfGI2ZLwuF0OThhSJygfjFAtEn9E',
    appId: '1:166422488084:web:55d61fab870f0cd54cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    authDomain: 'buildapplications-27ce1.firebaseapp.com',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    measurementId: 'G-YD8FSDN57R',
  );

}